geometry_msgs/Point min
geometry_msgs/Point max
geometry_msgs/Point current_position
int8 frontier_amount
uint32 request_number
uint32 request_id
bool new_request
uint32 global_search_it
uint32 max_distance
---
bool success
uint32 frontiers_found
uint32 global_search_it
frontiers_msgs/VoxelMsg[] frontiers